trigger:
- master

pool:
  default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt update
    sudo apt install -y openjdk-11-jdk
    sudo apt install -y tomcat9 tomcat9-admin
    sudo chmod 777 build.sh
    sudo rm -rf ROOT.war
    ./build.sh
    sudo rm -rf /var/lib/tomcat9/webapps/*
    sudo cp ROOT.war /var/lib/tomcat9/webapps
    sudo systemctl restart tomcat9
  displayName: 'Deploying tomcat application'
