name: Deploy to Tomcat9
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Deploy
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          sudo apt install -y tomcat10 tomcat10-admin
          sudo chmod 777 build.sh
          sudo rm -rf ROOT.war
          ./build.sh
          sudo rm -rf /var/lib/tomcat10/webapps/*
          sudo cp ROOT.war /var/lib/tomcat10/webapps/
          sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/
          sudo systemctl start tomcat10
