version: "3.8"

services:
  nginx-app:
    build:
      dockerfile: Dockerfile.nginx
    container_name: nginx-html-container
    ports:
      - "8081:80"
    restart: always

  tomcat-app:
    build:
      dockerfile: Dockerfile.tomcat
    container_name: tomcat-war-container
    ports:
      - "8082:8080"
    restart: always
